/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Project;

import javax.swing.*;

/**
 *
 * @author HRD-LAB1
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        this.setSize(1039,1068);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        guestsQty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roomType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        arrivalMonth = new javax.swing.JComboBox<>();
        arrivalYear = new javax.swing.JComboBox<>();
        arrivalDate = new javax.swing.JComboBox<>();
        arrivalTime = new javax.swing.JTextField();
        arrivalPeriod = new javax.swing.JComboBox<>();
        departDate = new javax.swing.JComboBox<>();
        departMonth = new javax.swing.JComboBox<>();
        departYear = new javax.swing.JComboBox<>();
        departTime = new javax.swing.JTextField();
        departPeriod = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        noPickup = new javax.swing.JRadioButton();
        yesPickup = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        request = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        submitButton = new java.awt.Button();

        setPreferredSize(new java.awt.Dimension(1039, 1068));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 25)); // NOI18N
        jLabel3.setText("Hotel Booking");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, 43));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));
        getContentPane().add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 135, 35));
        getContentPane().add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 135, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setText("First Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        maleButton.setText("Male");
        getContentPane().add(maleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 62, 35));

        femaleButton.setText("Female");
        getContentPane().add(femaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, -1, 35));

        guestsQty.setToolTipText("");
        getContentPane().add(guestsQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 317, 35));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Number of Guests");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Room Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        roomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard Room (1 to 2 people)", "Family Room (1 to 4 people)", "Private Room (1 to 3 people)", "Male Dorm Room (6 people)", "Female Dorm Room (6 people)", "Mix Dorm Room (6 people)" }));
        getContentPane().add(roomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 277, 36));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Arrival Date and Time");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Departure Date and Time");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, -1, -1));

        arrivalMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(arrivalMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 173, 36));

        arrivalYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        getContentPane().add(arrivalYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 90, 36));

        arrivalDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(arrivalDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 74, 36));
        getContentPane().add(arrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 113, 35));

        arrivalPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        getContentPane().add(arrivalPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, -1, 36));

        departDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(departDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 74, 36));

        departMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(departMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 173, 36));

        departYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        getContentPane().add(departYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 90, 36));

        departTime.setToolTipText("");
        getContentPane().add(departTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, 113, 35));

        departPeriod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        getContentPane().add(departPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 640, -1, 36));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Free Pickup?");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, -1, -1));

        noPickup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noPickup.setText("No, thanks - I'll make my own way there");
        getContentPane().add(noPickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 720, -1, -1));

        yesPickup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yesPickup.setText("Yes, please - Pick me up on arrival!");
        getContentPane().add(yesPickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel12.setText("Special Requests");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, -1, -1));
        getContentPane().add(request, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 934, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg pic (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(998, 314));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 362));

        submitButton.setBackground(new java.awt.Color(63, 114, 175));
        submitButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setLabel("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 900, 115, 58));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String uFirstName = firstName.getText();
        String uLastName = lastName.getText();
        String uRoomType = (String) roomType.getSelectedItem();
        String uRequest = request.getText();
        String uGender = ""; 
    

        if (maleButton.isSelected()) {
            uGender = "Male";
        } else if (femaleButton.isSelected()) {
            uGender = "Female";
        }
    

        String uGuestsQty = guestsQty.getText();
    

        String uArrivalDate = arrivalDate.getSelectedItem().toString() + " " +
                          arrivalMonth.getSelectedItem().toString() + " " +
                          arrivalYear.getSelectedItem().toString() + " " +
                          arrivalTime.getText() + " " +
                          arrivalPeriod.getSelectedItem().toString();
    

        String uDepartDate = departDate.getSelectedItem().toString() + " " +
                         departMonth.getSelectedItem().toString() + " " +
                         departYear.getSelectedItem().toString() + " " +
                         departTime.getText() + " " +
                         departPeriod.getSelectedItem().toString();
    

        String uPickup = "";
        if (yesPickup.isSelected()) {
            uPickup = "Yes, please pick me up on arrival!";
        } else if (noPickup.isSelected()) {
            uPickup = "No, I will make my own way there.";
        }
    

        if (uFirstName.isEmpty() || uLastName.isEmpty() || uGuestsQty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    

        String message = """
                         Booking Summary:
                         
                         Name: """ + uFirstName + " " + uLastName + "\n" +
                     "Gender: " + uGender + "\n" +
                     "Room Type: " + uRoomType + "\n" +
                     "Number of Guests: " + uGuestsQty + "\n" +
                     "Arrival: " + uArrivalDate + "\n" +
                     "Departure: " + uDepartDate + "\n" +
                     "Pickup: " + uPickup + "\n" +
                     "Special Requests: " + uRequest;
    
        JOptionPane.showMessageDialog(this, message, "Booking Confirmation", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_submitButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> arrivalDate;
    private javax.swing.JComboBox<String> arrivalMonth;
    private javax.swing.JComboBox<String> arrivalPeriod;
    private javax.swing.JTextField arrivalTime;
    private javax.swing.JComboBox<String> arrivalYear;
    private javax.swing.JComboBox<String> departDate;
    private javax.swing.JComboBox<String> departMonth;
    private javax.swing.JComboBox<String> departPeriod;
    private javax.swing.JTextField departTime;
    private javax.swing.JComboBox<String> departYear;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField guestsQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JRadioButton noPickup;
    private javax.swing.JTextField request;
    private javax.swing.JComboBox<String> roomType;
    private java.awt.Button submitButton;
    private javax.swing.JRadioButton yesPickup;
    // End of variables declaration//GEN-END:variables
}
